SELECT NAME, DB_UNIQUE_NAME, OPEN_MODE, LOG_MODE, FLASHBACK_ON, FORCE_LOGGING FROM V$DATABASE;
SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;
SELECT  PROCESS, STATUS, SEQUENCE# FROM V$MANAGED_STANDBY;
ARCHIVE LOG LIST;

select * from v$log_history;

SELECT log_mode FROM v$database;

ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
archive log list;

SELECT * FROM v$log_history;

select GROUP#,THREAD#,SEQUENCE#,bytes/1024/1024, MEMBERS,STATUS from v$log;

SELECT TYPE, MEMBER FROM V$LOGFILE ORDER BY GROUP#;

select thread#, group#, sequence#, status, bytes/1024/1024 from v$standby_log;

SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;

SELECT PROTECTION_MODE
FROM V$DATABASE;

SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE,PROTECTION_MODE FROM V$DATABASE;

ALTER SESSION SET nls_date_format='DD-MON-YYYY HH24:MI:SS';
SELECT SEQUENCE#, FIRST_TIME, NEXT_TIME, APPLIED FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;
ARCHIVE LOG LIST;

SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;

SELECT * FROM  GV$ARCHIVE_DEST_STATUS WHERE DEST_ID <= 2;
select protection_mode,database_role,protection_level,open_mode from v$database;
SELECT SEQUENCE#, FIRST_TIME, NEXT_TIME, APPLIED FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;


 select protection_mode,protection_level from v$database;
 	INSERT INTO TEST1 VALUES (14, 'vu');
	COMMIT;
 --
SELECT ARCH.THREAD# "Thread", ARCH.SEQUENCE# "Last Sequence Received",
APPL.SEQUENCE# "Last Sequence Applied",
(ARCH.SEQUENCE# - APPL.SEQUENCE#) "Difference" 
FROM
(SELECT THREAD# ,SEQUENCE# FROM V$ARCHIVED_LOG WHERE (THREAD#,FIRST_TIME )
IN (SELECT THREAD#,MAX(FIRST_TIME) 
FROM V$ARCHIVED_LOG GROUP BY THREAD#)) ARCH,
(SELECT THREAD# ,SEQUENCE# FROM V$LOG_HISTORY WHERE (THREAD#,FIRST_TIME )
IN (SELECT THREAD#,MAX(FIRST_TIME) 
FROM V$LOG_HISTORY GROUP BY THREAD#)) APPL
WHERE
ARCH.THREAD# = APPL.THREAD#
ORDER BY 1;
--
	INSERT INTO TEST1 VALUES (61, 'help');
	COMMIT;