
SELECT NAME, DB_UNIQUE_NAME, OPEN_MODE, LOG_MODE, FLASHBACK_ON, FORCE_LOGGING FROM V$DATABASE;

SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;

SELECT SEQUENCE#, FIRST_TIME, NEXT_TIME, APPLIED FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;
SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;

SELECT  PROCESS, STATUS, SEQUENCE# FROM V$MANAGED_STANDBY;

SELECT * FROM  GV$ARCHIVE_DEST_STATUS;

SELECT DB_UNIQUE_NAME, SWITCHOVER_STATUS, DATABASE_ROLE, OPEN_MODE FROM V$DATABASE;

select * from dba_data_files;

select GROUP#,THREAD#,SEQUENCE#,bytes/1024/1024, MEMBERS,STATUS from v$log;
select thread#, group#, sequence#, status, bytes/1024/1024 from v$standby_log;
SELECT TYPE, MEMBER FROM V$LOGFILE ORDER BY GROUP#;
--
SELECT 
ARCH.THREAD# "Instance", 
ARCH.SEQUENCE# "Log nh?n m?i nh?t",
APPL.SEQUENCE# "Log ?ã áp d?ng",
(ARCH.SEQUENCE# - APPL.SEQUENCE#) "?? tr?" 
FROM
    (SELECT THREAD# ,SEQUENCE# 
        FROM V$ARCHIVED_LOG 
        WHERE (THREAD#, FIRST_TIME)
            IN (SELECT THREAD#, MAX(FIRST_TIME)
                    FROM V$ARCHIVED_LOG 
                    GROUP BY THREAD#)
    ) ARCH,
    (SELECT THREAD# ,SEQUENCE# 
        FROM V$LOG_HISTORY 
        WHERE (THREAD#, FIRST_TIME)
            IN (SELECT THREAD#, MAX(FIRST_TIME) 
                    FROM V$LOG_HISTORY 
                    GROUP BY THREAD#)
    ) APPL
WHERE
    ARCH.THREAD# = APPL.THREAD#;